services:
  database:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: dog-api
      POSTGRES_PASSWORD: dog-api
      POSTGRES_DB: dog-api
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
